spring:
  application:
    name: cloudsql-jpa
  profiles:
    include: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;database_to_upper=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: none # create-drop (without init sql scripts)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  sql:
    init:
      mode: embedded
      platform: h2
      encoding: UTF-8
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
---
spring:
  config:
    activate:
      on-profile: gcp
  cloud:
    gcp:
      sql:
        enabled: true
        instance-connection-name: ${CONNECTION_NAME}
        database-name: codelab
        credentials:
          encoded-key: ${CREDENTIAL}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql-guest
    password: ${PASSWORD:password}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default
---
spring:
  config:
    activate:
      on-profile: auto-ddl # gradlew clean bootRun --args='--spring.profiles.active=auto-ddl'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;database_to_upper=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default
